#!/usr/bin/env python3

import sys
import subprocess
import json
import os
from functions import *




if sys.argv[1] == "diff":
    
    #Generating diff for two directories
    if( len(sys.argv) < 3 ):
        raise Exception("Please input base directory.")
    elif( len(sys.argv) < 4 ):
        raise Exception("Please input directory to be compared with.")


    base_dir = sys.argv[2]
    comp_dir = sys.argv[3]


    #diffing
    dir_diff_object = generate_dir_diffs( base_dir, comp_dir )

    if len(sys.argv) > 4:
        filepath = sys.argv[4]
        file = open(filepath, "w")
        json.dump(dir_diff_object, file)
        file.close()
    else:
        print(dir_diff_object)








if sys.argv[1] == "patch":
    
    #patching
    if len(sys.argv) < 3:
        raise Exception("Please input directory to be patched.")
    elif len(sys.argv) < 4:
        raise Exception("Please input patch file.")
    

    #creating dir diff object
    patchfile = sys.argv[3]
    patchfile_stream = open(patchfile, "r")
    dir_diff_object = json.load(patchfile_stream)
    patchfile_stream.close()


    def dir_patch(dir, dir_diff_object):
        
        file_object = dir_diff_object["files"]
        
        for file in file_object["files_to_delete"]:
            bash_execute(f"rm {dir}/{file}")
        
        build(dir, file_object["files_to_add"])

        bash_execute(f"touch {dir}/temppatch8132")
        for file, diff in file_object["file_diffs"]:
            temp_patch_file = open(f"{dir}/temppatch8132", "w")
            temp_patch_file.write(diff)
            temp_patch_file.close()
            bash_execute(f"patch {dir}/{file} {dir}/temppatch8132")
        bash_execute(f"rm {dir}/temppatch8132")


        
        dir_object = dir_diff_object["dirs"]

        for directory in dir_object["dirs_to_delete"]:
            bash_execute(f"rm -r {dir}/{directory}")
        
        build( dir, dir_object["dirs_to_build"] )

        # for directory_diff_object in dir_object["dir_diffs"]:
        #     dir_patch( f"{dir}/{")

        
    dir_patch(sys.argv[2], dir_diff_object)