#!/usr/bin/env python3

import sys
import subprocess
import json
from functions import *




#Generating diff for two directories

if( len(sys.argv) < 2 ):
    raise Exception("Please input base directory.")
elif( len(sys.argv) < 3 ):
    raise Exception("Please input directory to be compared with.")


base_dir = sys.argv[1]
comp_dir = sys.argv[2]

file_diff_object = generate_file_diffs( base_dir, comp_dir )

base_dir_dirs = generate_dir_list(base_dir)
comp_dir_dirs = generate_dir_list(comp_dir)





















